### ISSUE TITLE
Error when publishing msg.

### ISSUE THREAD

**Issue by phongyu** [kmamykin/aws-mqtt#4]
I just tried to send a simple msg to AWSIoT 

const publish = AWSMqtt.publisher({
    WebSocket: WebSocket,
    region: AWS.config.region,
    credentials: AWS.config.credentials,
    endpoint: 'xxxxxxxxx.iot.eu-west-1.amazonaws.com'
})

 publish('/myTopic', 'Hello World').then(() => console.log('Success'), console.error)

Error: MQTT went offline
    at Client.<anonymous> (/var/app/current/node_modules/aws-mqtt/lib/publisher.js:32:16)
    at Client.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Client.emit (events.js:185:7)
    at Client.MqttClient._setupReconnect (/var/app/current/node_modules/mqtt/lib/client.js:590:12)
    at emitOne (events.js:101:20)
    at Client.emit (events.js:188:7)
    at WebSocketStream.f (/var/app/current/node_modules/once/once.js:25:25)
    at emitOne (events.js:101:20)
    at WebSocketStream.emit (events.js:188:7)

Please advice me.

**Comment by OmniPotent42** [comment]
I also have this issue

**Comment by kmamykin** [comment]
Can anyone provide a minimum example that shows this problem?

**Comment by garethmcc** [comment]
Is this still an issue for you guys? I am currently struggling with this issue and all parameters seem to be correct as far as I can tell.

**Comment by kmamykin** [comment]
Just released 1.0.0 - could you please verify this version works for you?

Previously published version was broken due to dependencies (`mqtt` and `aws-signature-v4`) releases that broke this package. I now pinned those to the versions that I tested to work.
